import * as vscode from 'vscode';

interface TreeIcon {
    iconPath: vscode.ThemeIcon;
    resourceUri?: vscode.Uri;
}

// ThemeIcon.File uses the active VS Code file icon theme. A representative file
// name lets the theme resolve the corresponding language icon without bundling
// a separate set of SVG logos.
const languageIconFileNames: Readonly<Record<string, string>> = {
    abap: 'language.abap',
    actionscript: 'language.as',
    ada: 'language.adb',
    agda: 'language.agda',
    apacheconf: '.htaccess',
    apacheconfig: '.htaccess',
    apex: 'language.cls',
    apl: 'language.apl',
    applescript: 'language.applescript',
    assembly: 'language.asm',
    astro: 'language.astro',
    awk: 'language.awk',
    batchfile: 'language.bat',
    bicep: 'language.bicep',
    blade: 'language.blade.php',
    c: 'language.c',
    'c#': 'language.cs',
    'c++': 'language.cpp',
    'c2hs haskell': 'language.hs',
    ceylon: 'language.ceylon',
    clojure: 'language.clj',
    cmake: 'CMakeLists.txt',
    cobol: 'language.cob',
    coffeescript: 'language.coffee',
    'common lisp': 'language.lisp',
    coq: 'language.v',
    crystal: 'language.cr',
    css: 'language.css',
    cuda: 'language.cu',
    cython: 'language.pyx',
    d: 'language.d',
    dart: 'language.dart',
    'debian package control file': 'control',
    dockerfile: 'Dockerfile',
    ejs: 'language.ejs',
    elixir: 'language.ex',
    elm: 'language.elm',
    emberscript: 'language.em',
    'emacs lisp': 'language.el',
    erlang: 'language.erl',
    'f#': 'language.fs',
    fish: 'language.fish',
    fortran: 'language.f90',
    'gcc machine description': 'language.c',
    gdscript: 'language.gd',
    'gentoo ebuild': 'language.ebuild',
    'gentoo eclass': 'language.eclass',
    'git attributes': '.gitattributes',
    'git config': '.gitconfig',
    gleam: 'language.gleam',
    glsl: 'language.glsl',
    go: 'language.go',
    'go checksums': 'language.go',
    'go module': 'language.go',
    gradle: 'build.gradle',
    graphql: 'schema.graphql',
    groovy: 'language.groovy',
    'groovy server pages': 'language.gsp',
    hack: 'language.hack',
    haml: 'language.haml',
    handlebars: 'language.hbs',
    haskell: 'language.hs',
    haxe: 'language.hx',
    hcl: 'language.hcl',
    html: 'index.html',
    idris: 'language.idr',
    java: 'Language.java',
    'jar manifest': 'MANIFEST.MF',
    'java properties': 'language.properties',
    'java server pages': 'language.jsp',
    javascript: 'language.js',
    'javascript+erb': 'language.js.erb',
    'jest snapshot': 'language.snap',
    'jetbrains mps': 'language.mps',
    jinja: 'language.jinja',
    json: 'language.json',
    json5: 'language.json5',
    jsonnet: 'language.jsonnet',
    'json with comments': 'language.jsonc',
    julia: 'language.jl',
    'jupyter notebook': 'language.ipynb',
    kotlin: 'language.kt',
    labview: 'language.lvproj',
    lean: 'language.lean',
    less: 'language.less',
    'linux kernel module': 'language.c',
    liquid: 'language.liquid',
    lua: 'language.lua',
    makefile: 'Makefile',
    markdown: 'language.md',
    matlab: 'language.m',
    mdx: 'language.mdx',
    meson: 'meson.build',
    'microsoft visual studio solution': 'language.sln',
    mojo: 'language.mojo',
    move: 'language.move',
    nginx: 'nginx.conf',
    nim: 'language.nim',
    nix: 'language.nix',
    'npm config': '.npmrc',
    numpy: 'language.py',
    nunjucks: 'language.njk',
    nushell: 'language.nu',
    'objective-c': 'language.m',
    'objective-c++': 'language.mm',
    ocaml: 'language.ml',
    odin: 'language.odin',
    'open policy agent': 'language.rego',
    openscad: 'language.scad',
    pascal: 'language.pas',
    perl: 'language.pl',
    php: 'language.php',
    plpgsql: 'language.pgsql',
    postcss: 'language.css',
    powershell: 'language.ps1',
    processing: 'language.pde',
    prolog: 'language.pro',
    'protocol buffer': 'language.proto',
    pug: 'language.pug',
    purebasic: 'language.pb',
    purescript: 'language.purs',
    python: 'language.py',
    'python console': 'language.py',
    'python traceback': 'language.py',
    qmake: 'language.qml',
    qml: 'language.qml',
    'qt script': 'language.qml',
    r: 'language.r',
    racket: 'language.rkt',
    raku: 'language.raku',
    reason: 'language.re',
    rescript: 'language.res',
    rmarkdown: 'language.rmd',
    roff: 'language.roff',
    ruby: 'language.rb',
    rust: 'language.rs',
    sass: 'language.sass',
    scala: 'language.scala',
    scheme: 'language.scm',
    scss: 'language.scss',
    'selinux policy': 'language.te',
    shell: 'language.sh',
    smali: 'language.smali',
    solidity: 'language.sol',
    sql: 'language.sql',
    ssh: 'language.ssh',
    'ssh config': 'language.ssh',
    starlark: 'language.bzl',
    stylus: 'language.styl',
    svelte: 'language.svelte',
    swift: 'language.swift',
    systemverilog: 'language.sv',
    tcl: 'language.tcl',
    tex: 'language.tex',
    tsx: 'language.tsx',
    twig: 'language.twig',
    typescript: 'language.ts',
    'unity3d asset': 'language.asset',
    'unix assembly': 'language.s',
    vala: 'language.vala',
    verilog: 'language.v',
    vhdl: 'language.vhd',
    'vim help file': 'language.vim',
    'vim script': 'language.vim',
    'vim snippet': 'language.vim',
    'visual basic .net': 'language.vb',
    vue: 'language.vue',
    webassembly: 'language.wat',
    wgsl: 'language.wgsl',
    xml: 'language.xml',
    xslt: 'language.xsl',
    yaml: 'language.yml',
    zig: 'language.zig',
};

const repositoryIcon: TreeIcon = {
    iconPath: new vscode.ThemeIcon('repo'),
};

const unknownLanguageIcon: TreeIcon = {
    iconPath: new vscode.ThemeIcon('file-code'),
};

const getTreeIcon = (language: string): TreeIcon => {
    const normalizedLanguage = language.trim().toLowerCase();
    if (!normalizedLanguage) {
        return repositoryIcon;
    }

    const fileName = languageIconFileNames[normalizedLanguage];
    if (!fileName) {
        return unknownLanguageIcon;
    }

    return {
        iconPath: vscode.ThemeIcon.File,
        resourceUri: vscode.Uri.from({
            scheme: 'github-trending-language',
            path: `/icons/${fileName}`,
        }),
    };
};

export default getTreeIcon;
